spring:
  data:
    mongodb:
      uri: mongodb+srv://m220student:m220password@communis-fanau.mongodb.net/test
      database: communis

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
