spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: communis
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
